jupyterhub:
  hub:
    image: 
      name: remche/k8s-hub
      tag: sa-template-0.4
  singleuser:
    image:
      name: remche/k8s-notebook
      tag: v1.18.3
    serviceAccountName: '{username}'
    extraEnv:
      TERM: 'xterm'
    defaultUrl: '/lab'
