apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-nodes
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
---
{{ if $.Values.rbac.metrics }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-metrics
rules:
- apiGroups:
  - metrics.k8s.io
  resources:
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
---
{{ end }}
